ALTER TABLE depots ALTER COLUMN name NOT NULL;
ALTER TABLE depots ALTER COLUMN origin NOT NULL;
ALTER TABLE depots ALTER COLUMN mined NOT NULL;
ALTER TABLE ONLY depots ADD UNIQUE (name);
ALTER TABLE ONLY depots ADD UNIQUE (origin);

	
