ALTER TABLE revisions ALTER COLUMN depot_id NOT NULL;
ALTER TABLE revisions ALTER COLUMN changeset_id NOT NULL;
ALTER TABLE revisions ALTER COLUMN change_type NOT NULL;
ALTER TABLE revisions ALTER COLUMN source_id NOT NULL;
ALTER TABLE revisions ALTER COLUMN target_id NOT NULL;
ALTER TABLE revisions ALTER COLUMN confidence NOT NULL;
ALTER TABLE revisions ALTER COLUMN old_mode NOT NULL;
ALTER TABLE revisions ALTER COLUMN new_mode NOT NULL;
ALTER TABLE revisions ALTER COLUMN old_hash NOT NULL;
ALTER TABLE revisions ALTER COLUMN new_hash NOT NULL;
ALTER TABLE revisions ALTER COLUMN lines_in NOT NULL;
ALTER TABLE revisions ALTER COLUMN lines_out NOT NULL;
ALTER TABLE revisions ADD UNIQUE (changeset_id, target_id);
